Fix create roles race condition
decent-dao/fractal-contracts pull request #116
Opened 2024-10-24 16:23 UTC by DarksightKellar

Contract deployed on Sepolia: `0xB1ba8caa9a65f4Bf53a5D1A1bD5514dFc9bB7E35`

2024-10-24 23:01 UTC, adamgall requested changes

2024-10-24 23:01 UTC, adamgall commented on deployments/sepolia/DecentHats_0_1_0.json
Please remove the deployment artifacts from this PR, or, let's get this deployed on _all_ of the networks. I'd like contract deployments (on all chains) to happen "all at once" in the context of a PR.

2024-10-24 23:01 UTC, adamgall commented on deployments/sepolia/solcInputs/868499c9bf8e01dcdf8b61017b8261aa.json
See previous comment

2024-10-24 23:01 UTC, adamgall commented on contracts/DecentHats_0_1_0.sol
> +        hatsProtocol.transferHat(topHatId, address(this), msg.sender);
Can you please leave some natspec comments on this function, explaining how it's independent of the rest of the code in this contract, and why it exists, and the reasoning behind its implementation?

2024-10-25 15:30 UTC, adamgall approved these changes

2024-10-25 17:43 UTC, mudrila approved these changes
Noice!

2024-10-25 17:43 UTC, Da-Colon approved these changes

2024-10-25 18:35 UTC, merged