Declare subDAO via FractalRegistry
decent-dao/fractal-contracts pull request #22
Opened 2023-01-09 22:18 UTC by mudrila

## Description

This PR implements declaring `subDAO` for the `parentDAO` the similar way as declaring DAO name - via event.
This PR does not implement any actual storing of relationships as it seems debatable and not decided completely.

## Notes

I started writing tests for atomic sub DAO deployment including step of declaring created `subDAO` under `parentDAO`, but that turned out quite a long story - so I think we should create new issue for that, as it goes way further than scope of current issue.

## Issue / Notion doc (if applicable)

Closes #21 

## Testing

1. Run tests

## Screenshots (if applicable)

2023-01-09 23:46 UTC, herbig commented on contracts/FractalRegistry.sol
> +/// @notice These names are non-unique, and should not be used as the identifer of a DAO
These comments only apply to the `updateDAOName` function, so should be moved down there

2023-01-09 23:47 UTC, herbig commented on contracts/FractalRegistry.sol
> +/// @notice These names are non-unique, and should not be used as the identifer of a DAO
and maybe a not about what this contract does here now

2023-01-09 23:47 UTC, herbig approved these changes
Left a note about fixing a comment, but otherwise looks good to go!

2023-01-10 15:26 UTC, tbwebb22 requested changes
Nice, this looks great. Only change I'll request is to increment the version in Package.json, and `npm install`

Thanks!

2023-01-10 20:36 UTC, tbwebb22 approved these changes
LGTM!

2023-01-10 20:40 UTC, merged